<div id="head">beepagePHP: text paging system</div>

<div class="navigation">
<ul id="leftnav">
	<li><a href="../index.php">features</a></li>
	<li><a href="../compose.php">compose</a></li>
	<li><a href="index.php">admin</a></li>
	<li><a href="edit.php?f=users">&nbsp;&nbsp;edit users</a></li>
	<li><a href="edit.php?f=aliases">&nbsp;&nbsp;edit groups</a></li>
	<li><a href="edit.php?f=services">&nbsp;&nbsp;edit services</a></li>
	<li><a href="../credits.php">credits</a></li>
</ul>
<ul id="version">
	<li>stable version:<br> beepage 1.0.1</li>
</ul>

</div>
